module.exports = {
  SOURCE_TEXT: 'SOURCE_TEXT',
  DOCBLOCK_OPEN: 'DOCBLOCK_OPEN',
  DOCBLOCK_CLOSE: 'DOCBLOCK_CLOSE',
  DOCBLOCK_TITLE: 'DOCBLOCK_TITLE',
  DOCBLOCK_DESC: 'DOCBLOCK_DESC',
  DOCBLOCK_TAG: 'DOCBLOCK_TAG'
}
